language: rust

branches:
  only:
    - master

cache: cargo

script:
  - cargo doc --no-deps --release

deploy:
    provider: pages
    local-dir: target/doc
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    name: flyingB0tat0
    email: bot@baudisch.xyz
    keep-history: false
    allow-empty-commit: true
